on:
  push:
    branches: main
    tags: v*

name: Build

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        include:
          - target: x86_64-apple-darwin
            os: macos-10.15
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      
      - name: Upload built artifact
        uses: actions/upload-artifact@v2
        with:
          name: tfv2rd-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/tfv2rd
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all built artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Rename artifacts
        run: |
          mkdir release
          for binary_dir in artifacts/*
          do
            mv "${binary_dir}/tfv2rd" "release/$(basename $binary_dir)"
          done

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release/tfv2rd-*
